#!/bin/sh
VER=`date '+%y%m%d'`

if [ $# -ge 1 ] ; then
	VER=$1
fi

NAME=hipatch-$VER

rm -rf dist/tmp
mkdir -p dist/tmp/src
mkdir -p dist/tmp/diag

cp Makefile *.src *.inc *.cpp *.h dist/tmp/src
cp README.txt LICENSE hipatch.atr patchrom.exe hisio*.com dumpos.com dist/tmp

cp diag-read.atr diag-ext-read.atr diag-write.atr diag-ext-write.atr dist/tmp/diag

cd dist/tmp
zip -r ../$NAME.zip *
cd ..

rm -rf tmp
