#!/bin/sh
VER=`date '+%y%m%d'`

if [ $# -ge 1 ] ; then
	VER=$1
fi

NAME=hipatch-$VER

rm -rf dist/tmp
mkdir -p dist/tmp/src/patchdisk

cp Makefile *.src *.inc *.bin *.cpp *.h dist/tmp/src
cp hipatch.atr patchrom.exe dist/tmp

cd dist/tmp
zip -r ../$NAME *
cd ..

rm -rf tmp
